### ISSUE TITLE
RPC Node Variability

### ISSUE THREAD

**Issue by martelaxe** [Bitcoin-AI/icp-canister-bridge#2]
Modify the source code to allow for variable Remote Procedure Call (RPC) node configurations, enabling the bridge to interact with different EVM-based blockchains seamlessly.

**Comment by henrique1837** [comment]
Initiating Lightning -> EVM codding.

The idea is to change rsk_testnet.swapFromLightningNetwork and main.swapFromLightningNetwork to use chainId as input.
The canister should get chainIds and rpcUrls from https://chainid.network/chains.json in the act of being deployed (to be discussed, maybe we can also use rpcUrl as input).
By knowing the chainId the 'swapFromLightningNetwork' method can get url of the rpc and replace '${INFURA_KEY}' when needed.
An object can be created to make relation between chainIds and addresses of the wrapped bitcoin token from the network.

The frontend is being adapted to allow user select destiny chain for swaping from lightning to evm by fetching data from the chainid chains api.

**Comment by henrique1837** [comment]
Alby lnd1 had issues with channels, had to open channels and remove some liquidity to return working. Node info at https://github.com/getAlby/lightning-browser-extension/wiki/Test-setup 

The frontend of the dapp was changed to allow user select the destiny chain, the RPC url is used as parameter for 'main.swapFromLightning' method but we need to reconsider that in the new model there will be no smart contract at evms so we need to store proper wrapped btc addresses.

Result frontend allowing user select destiny chain

![image](https://github.com/Bitcoin-AI/icp-canister-bridge/assets/16599707/55697d83-a08f-48db-8f35-47fa19d6c2f1)

Result on evm - Bridge updates evm address balance (rsk testnet in this example)

![image](https://github.com/Bitcoin-AI/icp-canister-bridge/assets/16599707/15e72d63-bad1-468a-869f-2076e737cf1a)

In that first try we use https://chainid.network/chains.json to get rpcs and networks from frontend and smart contracts are still being used.

**Comment by henrique1837** [comment]
Swap from evm to ln tested on user interface using mumbai network, still need to adapt to use WBTC in evm chains that are not rsk.
![image](https://github.com/Bitcoin-AI/icp-canister-bridge/assets/16599707/d5e402aa-5225-4af7-8907-b83879e4a51c)

Once payment is done the transaction hash can be signed (to be implemented) and sent to the service, triggering the lightning payment to the user's invoice

![image](https://github.com/Bitcoin-AI/icp-canister-bridge/assets/16599707/b1128584-37c1-46fe-9754-5d71a0c68d30)

Once amount sent on evm is verified, lightning payment is done.

![image](https://github.com/Bitcoin-AI/icp-canister-bridge/assets/16599707/075604e0-a271-4802-a596-76336c113d30)

Most test lightning nodes from getalby are in maintence so a new local lnd node was set up using https://github.com/nostrassets/taproot-docker/tree/main/testnet as start point. 
Channels are being opened to be able to send sats to getalby LND1 that is being used by the service.

**Comment by henrique1837** [comment]
Still have not manage to send lightning transactions to getalby LND1 (not finding route, already opened 12 channels with a local testnet node and also increased inbound liquidity at getalbyLND1);

Invoices generate by the local test node can be paid by getalbyLND1;

A temporary solution is to use https://htlc.me/ (opened channel between getalbyLND1 and htlc.me) for paying invoices generated from getalbyLND1 and click "Check Invoice" button at step2 inside "Lightning to EVM" tab content.
Since we removed smart contract usage, the EVM transaction is returning error ``` {"code": -32602, "message": "Missing parameter, gasPrice, gas or value"}``` for rsk testnet and ```{"code": -32000, "message": "replacement transaction underpriced"}``` for mumbai. We should start merging ``feat/rpc-node-variability `` with  ``feat/transaction-type`` soon.

Evm to Lightning works using the local test node;

**Comment by henrique1837** [comment]
Mumbai and rsk testnet working, problems were related to getting gas price parameters (rsk) and a failed stucked tx due testing (mumbai, had to increase gasPrice manually).
Merging with ``feat/transaction-type`` started

**Comment by henrique1837** [comment]
``evm2ln``, ``ln2evm`` and ``evm2evm`` working in front end, starting checking expressjs service to allow usage of more evms nodes
